-- supabase/sql/20260526_registered_device_foundation_d1.sql
-- C.S.V. BEACON — D1 Registered Device Foundation
-- Purpose:
--   All application access shall be tied to a registered device identity.
--   Offline permission is deliberately separate from general device approval.
--
-- Scope of this migration:
--   - Adds registered device table.
--   - Adds request/status/admin RPC foundation.
--   - Does not yet enforce a global frontend block.
--   - Does not yet enforce device approval inside every existing business RPC.
--   - Does not activate offline sync.

begin;

create extension if not exists pgcrypto;

create table if not exists public.csvb_registered_devices (
  id uuid primary key default gen_random_uuid(),

  -- Browser/PWA-generated durable public identifier.
  -- This is not a hardware serial number. It is generated by the application and stored locally on the device/browser profile.
  device_public_id text not null unique,

  device_label text,
  device_type text not null default 'unknown'
    check (device_type in ('desktop','laptop','tablet','smartphone','shared_workstation','unknown')),
  platform text,
  browser_language text,
  screen_summary text,
  user_agent_summary text,

  -- Access control status.
  status text not null default 'pending'
    check (status in ('pending','approved','blocked','revoked')),

  -- Access scope. Company/vessel are copied from the requesting user's profile.
  company_id uuid,
  vessel_id uuid,

  requested_by uuid,
  requested_at timestamptz not null default now(),

  approved_by uuid,
  approved_at timestamptz,

  blocked_by uuid,
  blocked_at timestamptz,

  revoked_by uuid,
  revoked_at timestamptz,

  last_user_id uuid,
  last_seen_at timestamptz,

  -- Offline capability is separate from general device approval.
  offline_allowed boolean not null default false,
  offline_allowed_modules text[] not null default array[]::text[],

  notes text,
  metadata jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_csvb_registered_devices_company_status
  on public.csvb_registered_devices(company_id, status);

create index if not exists idx_csvb_registered_devices_vessel_status
  on public.csvb_registered_devices(vessel_id, status);

create index if not exists idx_csvb_registered_devices_last_seen
  on public.csvb_registered_devices(last_seen_at desc nulls last);

create index if not exists idx_csvb_registered_devices_requested_by
  on public.csvb_registered_devices(requested_by);

alter table public.csvb_registered_devices enable row level security;

-- No broad direct table access. All normal access goes through SECURITY DEFINER RPCs.
drop policy if exists csvb_registered_devices_no_direct_access on public.csvb_registered_devices;
create policy csvb_registered_devices_no_direct_access
  on public.csvb_registered_devices
  for all
  to authenticated
  using (false)
  with check (false);

create or replace function public.csvb_device_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_csvb_registered_devices_updated_at on public.csvb_registered_devices;
create trigger trg_csvb_registered_devices_updated_at
before update on public.csvb_registered_devices
for each row
execute function public.csvb_device_touch_updated_at();

create or replace function public.csvb_device_current_profile()
returns table (
  user_id uuid,
  username text,
  role text,
  company_id uuid,
  vessel_id uuid
)
language sql
security definer
set search_path = public
as $$
  select
    p.id as user_id,
    p.username::text as username,
    p.role::text as role,
    p.company_id,
    p.vessel_id
  from public.profiles p
  where p.id = auth.uid();
$$;

create or replace function public.csvb_device_is_platform_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role::text in ('super_admin','platform_owner')
  );
$$;

create or replace function public.csvb_device_is_company_admin_for(p_company_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role::text = 'company_admin'
      and p.company_id = p_company_id
  );
$$;

create or replace function public.csvb_device_can_admin_company(p_company_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select public.csvb_device_is_platform_admin()
      or public.csvb_device_is_company_admin_for(p_company_id);
$$;

create or replace function public.csvb_request_device_registration(
  p_device_public_id text,
  p_device_label text default null,
  p_device_type text default 'unknown',
  p_platform text default null,
  p_user_agent_summary text default null,
  p_browser_language text default null,
  p_screen_summary text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns table (
  device_id uuid,
  device_public_id text,
  status text,
  device_label text,
  device_type text,
  platform text,
  company_id uuid,
  vessel_id uuid,
  offline_allowed boolean,
  offline_allowed_modules text[],
  requested_at timestamptz,
  approved_at timestamptz,
  last_seen_at timestamptz,
  access_allowed boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile record;
  v_device record;
  v_device_type text;
  v_platform_admin boolean;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  if length(trim(coalesce(p_device_public_id, ''))) < 12 then
    raise exception 'Invalid device_public_id';
  end if;

  select * into v_profile
  from public.csvb_device_current_profile()
  limit 1;

  if v_profile.user_id is null then
    raise exception 'Profile not found for current user';
  end if;

  v_platform_admin := v_profile.role in ('super_admin','platform_owner');

  v_device_type := coalesce(nullif(trim(p_device_type), ''), 'unknown');
  if v_device_type not in ('desktop','laptop','tablet','smartphone','shared_workstation','unknown') then
    v_device_type := 'unknown';
  end if;

  insert into public.csvb_registered_devices (
    device_public_id,
    device_label,
    device_type,
    platform,
    user_agent_summary,
    browser_language,
    screen_summary,
    company_id,
    vessel_id,
    requested_by,
    last_user_id,
    last_seen_at,
    metadata
  ) values (
    trim(p_device_public_id),
    nullif(trim(coalesce(p_device_label, '')), ''),
    v_device_type,
    nullif(trim(coalesce(p_platform, '')), ''),
    left(coalesce(p_user_agent_summary, ''), 500),
    nullif(trim(coalesce(p_browser_language, '')), ''),
    nullif(trim(coalesce(p_screen_summary, '')), ''),
    case when v_platform_admin then null else v_profile.company_id end,
    v_profile.vessel_id,
    v_profile.user_id,
    v_profile.user_id,
    now(),
    coalesce(p_metadata, '{}'::jsonb)
  )
  on conflict (device_public_id) do update set
    device_label = coalesce(nullif(trim(coalesce(excluded.device_label, '')), ''), public.csvb_registered_devices.device_label),
    device_type = excluded.device_type,
    platform = coalesce(excluded.platform, public.csvb_registered_devices.platform),
    user_agent_summary = excluded.user_agent_summary,
    browser_language = excluded.browser_language,
    screen_summary = excluded.screen_summary,
    last_user_id = excluded.last_user_id,
    last_seen_at = now(),
    metadata = public.csvb_registered_devices.metadata || coalesce(excluded.metadata, '{}'::jsonb)
  returning * into v_device;

  return query
  select
    v_device.id,
    v_device.device_public_id,
    v_device.status,
    v_device.device_label,
    v_device.device_type,
    v_device.platform,
    v_device.company_id,
    v_device.vessel_id,
    v_device.offline_allowed,
    v_device.offline_allowed_modules,
    v_device.requested_at,
    v_device.approved_at,
    v_device.last_seen_at,
    (
      v_device.status = 'approved'
      and (
        v_platform_admin
        or v_device.company_id is null
        or v_device.company_id = v_profile.company_id
      )
    ) as access_allowed;
end;
$$;

create or replace function public.csvb_my_device_status(
  p_device_public_id text
)
returns table (
  device_id uuid,
  device_public_id text,
  status text,
  device_label text,
  device_type text,
  platform text,
  company_id uuid,
  vessel_id uuid,
  offline_allowed boolean,
  offline_allowed_modules text[],
  requested_at timestamptz,
  approved_at timestamptz,
  last_seen_at timestamptz,
  access_allowed boolean,
  access_reason text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile record;
  v_device record;
  v_platform_admin boolean;
  v_access_allowed boolean;
  v_reason text;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  select * into v_profile
  from public.csvb_device_current_profile()
  limit 1;

  if v_profile.user_id is null then
    raise exception 'Profile not found for current user';
  end if;

  v_platform_admin := v_profile.role in ('super_admin','platform_owner');

  select * into v_device
  from public.csvb_registered_devices d
  where d.device_public_id = trim(coalesce(p_device_public_id, ''))
  limit 1;

  if v_device.id is null then
    return query
    select
      null::uuid,
      trim(coalesce(p_device_public_id, '')),
      'not_registered'::text,
      null::text,
      null::text,
      null::text,
      null::uuid,
      null::uuid,
      false,
      array[]::text[],
      null::timestamptz,
      null::timestamptz,
      null::timestamptz,
      false,
      'Device has not requested registration.'::text;
    return;
  end if;

  update public.csvb_registered_devices d
  set last_user_id = v_profile.user_id,
      last_seen_at = now()
  where d.id = v_device.id
  returning * into v_device;

  if v_device.status <> 'approved' then
    v_access_allowed := false;
    v_reason := 'Device status is ' || v_device.status || '.';
  elsif not v_platform_admin and v_device.company_id is not null and v_device.company_id <> v_profile.company_id then
    v_access_allowed := false;
    v_reason := 'Device is registered to a different company.';
  else
    v_access_allowed := true;
    v_reason := 'Device approved.';
  end if;

  return query
  select
    v_device.id,
    v_device.device_public_id,
    v_device.status,
    v_device.device_label,
    v_device.device_type,
    v_device.platform,
    v_device.company_id,
    v_device.vessel_id,
    v_device.offline_allowed,
    v_device.offline_allowed_modules,
    v_device.requested_at,
    v_device.approved_at,
    v_device.last_seen_at,
    v_access_allowed,
    v_reason;
end;
$$;

create or replace function public.csvb_admin_list_registered_devices(
  p_status text default null,
  p_company_id uuid default null
)
returns table (
  device_id uuid,
  device_public_id text,
  status text,
  device_label text,
  device_type text,
  platform text,
  company_id uuid,
  vessel_id uuid,
  requested_by uuid,
  requested_by_username text,
  approved_by uuid,
  approved_by_username text,
  requested_at timestamptz,
  approved_at timestamptz,
  last_user_id uuid,
  last_user_username text,
  last_seen_at timestamptz,
  offline_allowed boolean,
  offline_allowed_modules text[],
  notes text,
  user_agent_summary text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile record;
  v_platform_admin boolean;
  v_company_scope uuid;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  select * into v_profile
  from public.csvb_device_current_profile()
  limit 1;

  if v_profile.user_id is null then
    raise exception 'Profile not found for current user';
  end if;

  v_platform_admin := v_profile.role in ('super_admin','platform_owner');

  if not v_platform_admin and v_profile.role <> 'company_admin' then
    raise exception 'Access denied';
  end if;

  v_company_scope := case
    when v_platform_admin then p_company_id
    else v_profile.company_id
  end;

  return query
  select
    d.id,
    d.device_public_id,
    d.status,
    d.device_label,
    d.device_type,
    d.platform,
    d.company_id,
    d.vessel_id,
    d.requested_by,
    req.username::text,
    d.approved_by,
    app.username::text,
    d.requested_at,
    d.approved_at,
    d.last_user_id,
    lastp.username::text,
    d.last_seen_at,
    d.offline_allowed,
    d.offline_allowed_modules,
    d.notes,
    d.user_agent_summary
  from public.csvb_registered_devices d
  left join public.profiles req on req.id = d.requested_by
  left join public.profiles app on app.id = d.approved_by
  left join public.profiles lastp on lastp.id = d.last_user_id
  where (p_status is null or d.status = p_status)
    and (v_company_scope is null or d.company_id = v_company_scope)
    and (v_platform_admin or d.company_id = v_profile.company_id)
  order by
    case d.status
      when 'pending' then 1
      when 'approved' then 2
      when 'blocked' then 3
      when 'revoked' then 4
      else 9
    end,
    d.requested_at desc;
end;
$$;

create or replace function public.csvb_admin_update_registered_device(
  p_device_id uuid,
  p_status text,
  p_offline_allowed boolean default null,
  p_offline_allowed_modules text[] default null,
  p_notes text default null
)
returns table (
  device_id uuid,
  device_public_id text,
  status text,
  device_label text,
  company_id uuid,
  vessel_id uuid,
  offline_allowed boolean,
  offline_allowed_modules text[],
  notes text,
  approved_at timestamptz,
  blocked_at timestamptz,
  revoked_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile record;
  v_device record;
  v_new_status text;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  v_new_status := trim(coalesce(p_status, ''));
  if v_new_status not in ('pending','approved','blocked','revoked') then
    raise exception 'Invalid status: %', p_status;
  end if;

  select * into v_profile
  from public.csvb_device_current_profile()
  limit 1;

  if v_profile.user_id is null then
    raise exception 'Profile not found for current user';
  end if;

  select * into v_device
  from public.csvb_registered_devices d
  where d.id = p_device_id
  limit 1;

  if v_device.id is null then
    raise exception 'Device not found';
  end if;

  if not public.csvb_device_can_admin_company(v_device.company_id) then
    raise exception 'Access denied';
  end if;

  update public.csvb_registered_devices d
  set
    status = v_new_status,
    offline_allowed = coalesce(p_offline_allowed, case when v_new_status = 'approved' then d.offline_allowed else false end),
    offline_allowed_modules = coalesce(p_offline_allowed_modules, case when v_new_status = 'approved' then d.offline_allowed_modules else array[]::text[] end),
    notes = coalesce(p_notes, d.notes),
    approved_by = case when v_new_status = 'approved' then v_profile.user_id else d.approved_by end,
    approved_at = case when v_new_status = 'approved' then now() else d.approved_at end,
    blocked_by = case when v_new_status = 'blocked' then v_profile.user_id else d.blocked_by end,
    blocked_at = case when v_new_status = 'blocked' then now() else d.blocked_at end,
    revoked_by = case when v_new_status = 'revoked' then v_profile.user_id else d.revoked_by end,
    revoked_at = case when v_new_status = 'revoked' then now() else d.revoked_at end
  where d.id = p_device_id
  returning * into v_device;

  return query
  select
    v_device.id,
    v_device.device_public_id,
    v_device.status,
    v_device.device_label,
    v_device.company_id,
    v_device.vessel_id,
    v_device.offline_allowed,
    v_device.offline_allowed_modules,
    v_device.notes,
    v_device.approved_at,
    v_device.blocked_at,
    v_device.revoked_at;
end;
$$;

create or replace function public.csvb_admin_approve_registered_device(
  p_device_id uuid,
  p_offline_allowed boolean default false,
  p_offline_allowed_modules text[] default array[]::text[],
  p_notes text default null
)
returns table (
  device_id uuid,
  device_public_id text,
  status text,
  device_label text,
  company_id uuid,
  vessel_id uuid,
  offline_allowed boolean,
  offline_allowed_modules text[],
  notes text,
  approved_at timestamptz,
  blocked_at timestamptz,
  revoked_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select *
  from public.csvb_admin_update_registered_device(
    p_device_id,
    'approved',
    p_offline_allowed,
    p_offline_allowed_modules,
    p_notes
  );
$$;

create or replace function public.csvb_admin_block_registered_device(
  p_device_id uuid,
  p_notes text default null
)
returns table (
  device_id uuid,
  device_public_id text,
  status text,
  device_label text,
  company_id uuid,
  vessel_id uuid,
  offline_allowed boolean,
  offline_allowed_modules text[],
  notes text,
  approved_at timestamptz,
  blocked_at timestamptz,
  revoked_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select *
  from public.csvb_admin_update_registered_device(
    p_device_id,
    'blocked',
    false,
    array[]::text[],
    p_notes
  );
$$;

create or replace function public.csvb_admin_revoke_registered_device(
  p_device_id uuid,
  p_notes text default null
)
returns table (
  device_id uuid,
  device_public_id text,
  status text,
  device_label text,
  company_id uuid,
  vessel_id uuid,
  offline_allowed boolean,
  offline_allowed_modules text[],
  notes text,
  approved_at timestamptz,
  blocked_at timestamptz,
  revoked_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select *
  from public.csvb_admin_update_registered_device(
    p_device_id,
    'revoked',
    false,
    array[]::text[],
    p_notes
  );
$$;

grant execute on function public.csvb_device_current_profile() to authenticated;
grant execute on function public.csvb_device_is_platform_admin() to authenticated;
grant execute on function public.csvb_device_is_company_admin_for(uuid) to authenticated;
grant execute on function public.csvb_device_can_admin_company(uuid) to authenticated;
grant execute on function public.csvb_request_device_registration(text, text, text, text, text, text, text, jsonb) to authenticated;
grant execute on function public.csvb_my_device_status(text) to authenticated;
grant execute on function public.csvb_admin_list_registered_devices(text, uuid) to authenticated;
grant execute on function public.csvb_admin_update_registered_device(uuid, text, boolean, text[], text) to authenticated;
grant execute on function public.csvb_admin_approve_registered_device(uuid, boolean, text[], text) to authenticated;
grant execute on function public.csvb_admin_block_registered_device(uuid, text) to authenticated;
grant execute on function public.csvb_admin_revoke_registered_device(uuid, text) to authenticated;

notify pgrst, 'reload schema';

commit;
